[app]
env = "local"
ip = "127.0.0.1"
host = "127.0.0.1:8000"
port = ":8000"
secure = false
debug = true

[database_master]
db = "Lv"
host = "127.0.0.1"
port = "3306"
username = "root"
password = "qwe123"

[database_slave]
db = "Lv"
host = "127.0.0.1"
port = "3306"
username = "root"
password = "qwe123"
